### ISSUE TITLE
Solr/Odoo v11 Integration

### ISSUE THREAD

**Issue by SaifIssaoui** [akretion/connector-search-engine#44]
Hi,
I am a beginner in odoo,
 and I want to know : is it possible to integrate apache solr with odoo 11? :thinking: 
Thanks for all :+1:

**Comment by rvalyi** [comment]
Hello @SaifIssaoui,

that's right, Akretion started prototyping noSQL connectors for Odoo with SolR back in 2013, using the sunburnt module (you can read things about the former design here https://github.com/akretion/connector-search-engine/issues/3) . And then, in order to optimize the time to market we moved to Algolia (which is not open source). The thing is the code changed quite a lot between 2013 and 2019, so you better port the former SolR connector from v7 to v11. The best you can do is inspire yourself with the v10 Algolia and now Elastic Search connectors:

1. https://github.com/akretion/connector-search-engine/tree/10.0/connector_algolia
2. https://github.com/akretion/connector-search-engine/pull/45

And may be try to fit my former v7 connector into the new model. In fact I cannot even find back my v7 solr module, may be we removed it from the repo by accident.

But you better think twice if the Elastic Search connector that was just contributed by Acsone wouldn't fit your need.

Alternatively, if you want, I think Akretion can re-develop the v7 SolR connector according the new framework and for v11 for something around 1800 euros (with tests passing but no support).

feel free to re-open the issue if you need.

**Comment by SaifIssaoui** [comment]
Thanks a lot ^_^

Le lun. 25 févr. 2019 à 16:50, Raphaël Valyi <notifications@github.com> a
écrit :
